# Generated by Django 4.0.5 on 2022-06-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, null=True, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('pais', models.CharField(max_length=250, null=True, verbose_name='País')),
                ('cep', models.CharField(max_length=9, null=True, verbose_name='CEP')),
                ('uf_endereco', models.CharField(max_length=50, null=True, verbose_name='Estado')),
                ('cidade', models.CharField(max_length=75, null=True, verbose_name='Município')),
                ('rua', models.CharField(max_length=60, null=True, verbose_name='Logradouro')),
                ('casa', models.CharField(max_length=5, null=True, verbose_name='Número')),
                ('complemento_endereco', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('cpf', models.CharField(max_length=16, null=True, verbose_name='CPF')),
                ('numero_pis', models.CharField(max_length=11, null=True, verbose_name='Número do PIS')),
                ('senha', models.CharField(max_length=30, null=True, verbose_name='Senha')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
